
import React from 'react';
import { 
  Home, 
  CloudSun, 
  TrendingUp, 
  ClipboardList, 
  Wheat, 
  Droplets, 
  Thermometer, 
  Navigation,
  Plus,
  Trash2,
  Edit2
} from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    appName: "Kisan Saathi",
    home: "Home",
    weather: "Weather",
    prices: "Market Prices",
    records: "Records",
    todayTemp: "Today's Temp",
    topPrices: "Top Crop Prices",
    recentRecords: "Recent Records",
    humidity: "Humidity",
    rainfall: "Rainfall",
    forecast: "5-Day Forecast",
    location: "Location",
    mandi: "Mandi",
    price: "Price",
    updated: "Updated",
    addRecord: "Add New Record",
    cropName: "Crop Name",
    sowingDate: "Sowing Date",
    harvestDate: "Expected Harvest",
    quantity: "Quantity (kg/qtl)",
    expenses: "Expenses (₹)",
    income: "Income (₹)",
    save: "Save Record",
    delete: "Delete",
    edit: "Edit",
    noRecords: "No records found. Start adding your farm data!",
    detectLocation: "Detecting Location...",
    selectMandi: "Select Mandi/State",
    allStates: "All States",
    searchCrop: "Search Crop",
    trendUp: "Rising",
    trendDown: "Falling",
    stable: "Stable"
  },
  hi: {
    appName: "किसान साथी",
    home: "मुख्य",
    weather: "मौसम",
    prices: "मंडी भाव",
    records: "रिकॉर्ड",
    todayTemp: "आज का तापमान",
    topPrices: "प्रमुख फसल भाव",
    recentRecords: "हाल के रिकॉर्ड",
    humidity: "नमी",
    rainfall: "बारिश",
    forecast: "5-दिन का पूर्वानुमान",
    location: "स्थान",
    mandi: "मंडी",
    price: "भाव",
    updated: "अपडेट किया गया",
    addRecord: "नया रिकॉर्ड जोड़ें",
    cropName: "फसल का नाम",
    sowingDate: "बुवाई की तारीख",
    harvestDate: "अनुमानित कटाई",
    quantity: "मात्रा (किलो/क्विंटल)",
    expenses: "खर्च (₹)",
    income: "आय (₹)",
    save: "रिकॉर्ड सहेजें",
    delete: "हटाएं",
    edit: "बदलें",
    noRecords: "कोई रिकॉर्ड नहीं मिला। डेटा जोड़ना शुरू करें!",
    detectLocation: "स्थान का पता लगाया जा रहा है...",
    selectMandi: "मंडी/राज्य चुनें",
    allStates: "सभी राज्य",
    searchCrop: "फसल खोजें",
    trendUp: "बढ़ रहा है",
    trendDown: "घट रहा है",
    stable: "स्थिर"
  },
  mr: {
    appName: "बळीराजा",
    home: "मुख्य",
    weather: "हवामान",
    prices: "बाजार भाव",
    records: "नोंदी",
    todayTemp: "आजचे तापमान",
    topPrices: "प्रमुख पीक भाव",
    recentRecords: "अलीकडील नोंदी",
    humidity: "आद्रता",
    rainfall: "पाऊस",
    forecast: "5-दिवसांचा अंदाज",
    location: "ठिकाण",
    mandi: "मंडी",
    price: "दर",
    updated: "अपडेट",
    addRecord: "नवीन नोंद करा",
    cropName: "पिकाचे नाव",
    sowingDate: "पेरणीची तारीख",
    harvestDate: "कापणीचा अंदाज",
    quantity: "प्रमाण (किलो/क्विंटल)",
    expenses: "खर्च (₹)",
    income: "उत्पन्न (₹)",
    save: "नोंद जतन करा",
    delete: "हटवा",
    edit: "संपादन करा",
    noRecords: "नोंदी सापडल्या नाहीत. माहिती भरण्यास सुरुवात करा!",
    detectLocation: "ठिकाण शोधत आहे...",
    selectMandi: "मंडी/राज्य निवडा",
    allStates: "सर्व राज्ये",
    searchCrop: "पीक शोधा",
    trendUp: "वाढत आहे",
    trendDown: "कमी होत आहे",
    stable: "स्थिर"
  }
};

export const MOCK_PRICES = [
  { id: '1', crop: 'Wheat (गहू)', mandi: 'Nagpur', state: 'Maharashtra', price: 2450, unit: 'qtl', trend: 'up', updatedAt: '2024-05-20' },
  { id: '2', crop: 'Onion (कांदा)', mandi: 'Lasalgaon', state: 'Maharashtra', price: 1800, unit: 'qtl', trend: 'down', updatedAt: '2024-05-20' },
  { id: '3', crop: 'Cotton (कापूस)', mandi: 'Rajkot', state: 'Gujarat', price: 7200, unit: 'qtl', trend: 'stable', updatedAt: '2024-05-20' },
  { id: '4', crop: 'Rice (तांदूळ)', mandi: 'Karnal', state: 'Haryana', price: 3500, unit: 'qtl', trend: 'up', updatedAt: '2024-05-20' },
  { id: '5', crop: 'Potato (बटाटा)', mandi: 'Agra', state: 'UP', price: 1200, unit: 'qtl', trend: 'up', updatedAt: '2024-05-20' },
];

export const MOCK_WEATHER = {
  temp: 32,
  condition: "Sunny",
  humidity: 45,
  rainfall: "0mm",
  location: "Nashik, Maharashtra",
  forecast: [
    { day: "Mon", temp: 33, icon: "sun" },
    { day: "Tue", temp: 31, icon: "cloud" },
    { day: "Wed", temp: 29, icon: "cloud-rain" },
    { day: "Thu", temp: 30, icon: "sun" },
    { day: "Fri", temp: 34, icon: "sun" },
  ]
};
